/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    directions: Direction;
    services: Service;
    offers: Offer;
    courses: Course;
    'fashion-collections': FashionCollection;
    'portfolio-cases': PortfolioCase;
    testimonials: Testimonial;
    pages: Page;
    leads: Lead;
    'booking-requests': BookingRequest;
    'payment-orders': PaymentOrder;
    'webhook-events': WebhookEvent;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    directions: DirectionsSelect<false> | DirectionsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'fashion-collections': FashionCollectionsSelect<false> | FashionCollectionsSelect<true>;
    'portfolio-cases': PortfolioCasesSelect<false> | PortfolioCasesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'booking-requests': BookingRequestsSelect<false> | BookingRequestsSelect<true>;
    'payment-orders': PaymentOrdersSelect<false> | PaymentOrdersSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'ru' | 'en') | ('uk' | 'ru' | 'en')[];
  globals: {
    home: Home;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'booking-settings': BookingSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
  };
  locale: 'uk' | 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  roles: ('owner' | 'editor' | 'support' | 'finance' | 'developer')[];
  active: boolean;
  adminLocale?: ('uk' | 'ru' | 'en') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Internal searchable asset name.
   */
  internalLabel: string;
  /**
   * Required human-reviewed alt text in UK, RU and EN.
   */
  alt: string;
  source: 'client' | 'generated' | 'licensed' | 'editorial';
  usageRightsStatus: 'pending' | 'approved' | 'restricted' | 'expired';
  modelReleaseStatus: 'not-applicable' | 'pending' | 'approved' | 'restricted';
  publicVisibility: boolean;
  isRealClientProof: boolean;
  replacementPriority: 'none' | 'replace-before-launch' | 'replace-when-approved';
  creator?: string | null;
  creditLine?: string | null;
  allowedUsageContexts?: ('home' | 'service' | 'course' | 'collection' | 'portfolio' | 'studio' | 'social')[] | null;
  /**
   * Leave empty only for approved no-expiry usage rights.
   */
  rightsExpiry?: string | null;
  /**
   * Internal provenance, license, prompt or release reference. Never public.
   */
  sourceMetadata?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    editorial?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions".
 */
export interface Direction {
  id: string;
  /**
   * Stable migration key. Never reuse for another entity.
   */
  legacyKey: string;
  /**
   * Stable, non-localized public route segment.
   */
  slug: string;
  title: string;
  summary: string;
  enabled: boolean;
  featured: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  canonicalKey: 'research' | 'realisation' | 'transformation' | 'corporate' | 'school' | 'collections';
  eyebrow?: string | null;
  narrative: string;
  processTitle: string;
  formatsTitle: string;
  formatNotes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  outcomesTitle: string;
  ctaTitle: string;
  ctaSummary: string;
  ctaService: string;
  ctaLabel: string;
  diagnosticLabel?: string | null;
  faqTitle?: string | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  countLabel?: string | null;
  availabilityValue?: string | null;
  availabilityLabel?: string | null;
  fittingValue?: string | null;
  fittingLabel?: string | null;
  catalogueTitle?: string | null;
  catalogueSummary?: string | null;
  materialsLabel?: string | null;
  inquiryTitle?: string | null;
  inquirySteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  heroMedia?: (string | null) | Media;
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (string | Service)[] | null;
  relatedCourses?: (string | Course)[] | null;
  relatedCollections?: (string | FashionCollection)[] | null;
  navigationVisible: boolean;
  /**
   * Controlled sections inside the fixed PURITY template. No raw HTML or CSS.
   */
  supplementaryLayout?:
    | (
        | {
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body: string;
            media: string | Media;
            mediaPosition: 'start' | 'end';
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading: string;
            items?:
              | (
                  | {
                      relationTo: 'services';
                      value: string | Service;
                    }
                  | {
                      relationTo: 'courses';
                      value: string | Course;
                    }
                  | {
                      relationTo: 'fashion-collections';
                      value: string | FashionCollection;
                    }
                  | {
                      relationTo: 'portfolio-cases';
                      value: string | PortfolioCase;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relationGrid';
          }
        | {
            heading: string;
            media: (string | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            items?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body: string;
            label: string;
            path: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Stable migration key. Never reuse for another entity.
   */
  legacyKey: string;
  /**
   * Stable, non-localized public route segment.
   */
  slug: string;
  title: string;
  summary: string;
  enabled: boolean;
  featured: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  primaryDirection: string | Direction;
  secondaryDirections?: (string | Direction)[] | null;
  audience: string;
  intro: string;
  formatsTitle: string;
  processTitle: string;
  outcomeTitle: string;
  commercialTitle: string;
  commercialStatusCopy: string;
  priceNote: string;
  nextStepTitle: string;
  nextStepSummary: string;
  formats: ('online' | 'studio' | 'remote-atelier' | 'in-person' | 'hybrid')[];
  formatPresentation?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  timingNote?: string | null;
  qualification?: string | null;
  gallery?: (string | Media)[] | null;
  relatedOffers?: (string | Offer)[] | null;
  relatedPortfolio?: (string | PortfolioCase)[] | null;
  relatedServices?: (string | Service)[] | null;
  relatedCourses?: (string | Course)[] | null;
  relatedCollections?: (string | FashionCollection)[] | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    action: 'inquiry' | 'booking-request' | 'deposit' | 'instant-payment' | 'waitlist' | 'contact';
  };
  /**
   * Controlled sections inside the fixed PURITY template. No raw HTML or CSS.
   */
  supplementaryLayout?:
    | (
        | {
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body: string;
            media: string | Media;
            mediaPosition: 'start' | 'end';
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading: string;
            items?:
              | (
                  | {
                      relationTo: 'services';
                      value: string | Service;
                    }
                  | {
                      relationTo: 'courses';
                      value: string | Course;
                    }
                  | {
                      relationTo: 'fashion-collections';
                      value: string | FashionCollection;
                    }
                  | {
                      relationTo: 'portfolio-cases';
                      value: string | PortfolioCase;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relationGrid';
          }
        | {
            heading: string;
            media: (string | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            items?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body: string;
            label: string;
            path: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: string;
  legacyKey: string;
  service?: (string | null) | Service;
  course?: (string | null) | Course;
  fashionCollection?: (string | null) | FashionCollection;
  sku: string;
  title: string;
  shortDescription: string;
  format: 'online' | 'studio' | 'remote-atelier' | 'in-person' | 'hybrid';
  pricingMode: 'fixed' | 'from' | 'range' | 'custom';
  checkoutMode: 'instant-payment' | 'deposit' | 'booking-request' | 'inquiry' | 'waitlist';
  commercialStatus: 'active' | 'coming-soon' | 'waitlist' | 'paused' | 'sold-out' | 'retired';
  prices?:
    | {
        currency: 'EUR' | 'UAH';
        /**
         * Fixed amount in integer minor units.
         */
        amount?: number | null;
        /**
         * Minimum amount in integer minor units.
         */
        minAmount?: number | null;
        /**
         * Maximum amount in integer minor units.
         */
        maxAmount?: number | null;
        id?: string | null;
      }[]
    | null;
  durationMinutes?: number | null;
  sessions?: number | null;
  deposit?: {
    amount?: number | null;
    percentage?: number | null;
  };
  effectiveFrom?: string | null;
  effectiveUntil?: string | null;
  termsVersion: string;
  enabled: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: string;
  /**
   * Stable migration key. Never reuse for another entity.
   */
  legacyKey: string;
  /**
   * Stable, non-localized public route segment.
   */
  slug: string;
  title: string;
  summary: string;
  enabled: boolean;
  featured: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  direction: string | Direction;
  description: string;
  eyebrow: string;
  serviceLabel: string;
  audienceTitle: string;
  formatTitle: string;
  methodTitle: string;
  prerequisitesTitle: string;
  curriculumTitle: string;
  curriculumSummary: string;
  outcomesTitle: string;
  outcomesSummary: string;
  commercialTitle: string;
  ctaTitle: string;
  ctaSummary: string;
  audience: string;
  prerequisites?: string | null;
  sessions: number;
  formats: ('online' | 'studio' | 'remote-atelier' | 'in-person' | 'hybrid')[];
  program?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  instructor?: string | null;
  credentials?: string | null;
  intakeNote?: string | null;
  relatedOffers?: (string | Offer)[] | null;
  media?: (string | Media)[] | null;
  availability: 'available' | 'coming-soon' | 'waitlist' | 'sold-out' | 'archived';
  relatedServices?: (string | Service)[] | null;
  relatedCollections?: (string | FashionCollection)[] | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    action: 'inquiry' | 'booking-request' | 'deposit' | 'instant-payment' | 'waitlist' | 'contact';
  };
  /**
   * Controlled sections inside the fixed PURITY template. No raw HTML or CSS.
   */
  supplementaryLayout?:
    | (
        | {
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body: string;
            media: string | Media;
            mediaPosition: 'start' | 'end';
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading: string;
            items?:
              | (
                  | {
                      relationTo: 'services';
                      value: string | Service;
                    }
                  | {
                      relationTo: 'courses';
                      value: string | Course;
                    }
                  | {
                      relationTo: 'fashion-collections';
                      value: string | FashionCollection;
                    }
                  | {
                      relationTo: 'portfolio-cases';
                      value: string | PortfolioCase;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relationGrid';
          }
        | {
            heading: string;
            media: (string | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            items?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body: string;
            label: string;
            path: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fashion-collections".
 */
export interface FashionCollection {
  id: string;
  /**
   * Stable migration key. Never reuse for another entity.
   */
  legacyKey: string;
  /**
   * Stable, non-localized public route segment.
   */
  slug: string;
  title: string;
  summary: string;
  enabled: boolean;
  featured: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  eyebrow?: string | null;
  narrative: string;
  stylingNotes?: string | null;
  stylingTitle: string;
  styling?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  factsTitle: string;
  facts?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  inquiryTitle: string;
  inquirySteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  materialsTitle: string;
  availabilityTitle: string;
  ctaTitle: string;
  ctaSummary: string;
  serviceLabel: string;
  collectionType: 'editorial' | 'commercial' | 'capsule' | 'collaboration' | 'seasonal';
  collaborationCredits?: string | null;
  materials?:
    | {
        material: string;
        id?: string | null;
      }[]
    | null;
  pieces?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  season?: string | null;
  year?: number | null;
  gallery: (string | Media)[];
  /**
   * Approved privacy-aware video URL; poster remains required in Media.
   */
  videoURL?: string | null;
  availability: 'available' | 'inquiry' | 'coming-soon' | 'sold-out' | 'archived';
  relatedOffers?: (string | Offer)[] | null;
  relatedServices?: (string | Service)[] | null;
  relatedCourse?: (string | null) | Course;
  rightsAndCredits: string;
  cta: {
    label: string;
    action: 'inquiry' | 'booking-request' | 'deposit' | 'instant-payment' | 'waitlist' | 'contact';
  };
  /**
   * Controlled sections inside the fixed PURITY template. No raw HTML or CSS.
   */
  supplementaryLayout?:
    | (
        | {
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body: string;
            media: string | Media;
            mediaPosition: 'start' | 'end';
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading: string;
            items?:
              | (
                  | {
                      relationTo: 'services';
                      value: string | Service;
                    }
                  | {
                      relationTo: 'courses';
                      value: string | Course;
                    }
                  | {
                      relationTo: 'fashion-collections';
                      value: string | FashionCollection;
                    }
                  | {
                      relationTo: 'portfolio-cases';
                      value: string | PortfolioCase;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relationGrid';
          }
        | {
            heading: string;
            media: (string | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            items?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body: string;
            label: string;
            path: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-cases".
 */
export interface PortfolioCase {
  id: string;
  /**
   * Stable migration key. Never reuse for another entity.
   */
  legacyKey: string;
  /**
   * Stable, non-localized public route segment.
   */
  slug: string;
  title: string;
  summary: string;
  enabled: boolean;
  featured: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  clientType: 'private' | 'corporate' | 'editorial' | 'collaboration';
  brief: string;
  constraints: string;
  research: string;
  process: string;
  result: string;
  services: (string | Service)[];
  media: (string | Media)[];
  hasBeforeAfter: boolean;
  /**
   * Internal consent/release reference; never public.
   */
  consentReference: string;
  isRealClientProof: boolean;
  usageRightsStatus: 'pending' | 'approved' | 'restricted' | 'expired';
  approvalStatus: 'pending' | 'approved' | 'rejected' | 'revoked';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  legacyKey: string;
  quote: string;
  attribution: string;
  roleOrCompany?: string | null;
  relatedService?: (string | null) | Service;
  relatedCase?: (string | null) | PortfolioCase;
  consentStatus: 'pending' | 'approved' | 'revoked';
  proofReference: string;
  enabled: boolean;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Stable migration key. Never reuse for another entity.
   */
  legacyKey: string;
  /**
   * Stable, non-localized public route segment.
   */
  slug: string;
  title: string;
  summary: string;
  enabled: boolean;
  featured: boolean;
  sortOrder: number;
  /**
   * Set automatically on first publication.
   */
  publishedAt?: string | null;
  pageType:
    | 'studio'
    | 'portfolio'
    | 'contacts'
    | 'privacy'
    | 'terms'
    | 'cookies'
    | 'payments'
    | 'cancellation-refunds'
    | 'consent'
    | 'service-state';
  eyebrow?: string | null;
  body: string;
  studioSignals?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  methodEyebrow?: string | null;
  methodTitle?: string | null;
  methodSteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  clientsTitle?: string | null;
  clientsSummary?: string | null;
  privateTitle?: string | null;
  corporateTitle?: string | null;
  directionsTitle?: string | null;
  ctaTitle?: string | null;
  ctaSummary?: string | null;
  formTitle?: string | null;
  formSummary?: string | null;
  heroMediaLabel?: string | null;
  standardsTitle?: string | null;
  standards?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  recordTitle?: string | null;
  recordSummary?: string | null;
  recordItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  currentTitle?: string | null;
  currentItems?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  flowTitle?: string | null;
  flowItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  secondaryCTALabel?: string | null;
  emptyEyebrow?: string | null;
  emptyTitle?: string | null;
  emptySummary?: string | null;
  emptyAction?: string | null;
  /**
   * Controlled PURITY sections. Raw HTML, CSS and arbitrary components are not supported.
   */
  layout?:
    | (
        | {
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body: string;
            media: string | Media;
            mediaPosition: 'start' | 'end';
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading: string;
            items?:
              | (
                  | {
                      relationTo: 'services';
                      value: string | Service;
                    }
                  | {
                      relationTo: 'courses';
                      value: string | Course;
                    }
                  | {
                      relationTo: 'fashion-collections';
                      value: string | FashionCollection;
                    }
                  | {
                      relationTo: 'portfolio-cases';
                      value: string | PortfolioCase;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relationGrid';
          }
        | {
            heading: string;
            media: (string | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            items?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body: string;
            label: string;
            path: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  sections?:
    | {
        heading: string;
        body: string;
        media?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  contactConfiguration?: {
    showMap?: boolean | null;
    corporateContext?: boolean | null;
  };
  legalVersion?: string | null;
  effectiveDate?: string | null;
  cta: {
    label: string;
    action: 'inquiry' | 'booking-request' | 'deposit' | 'instant-payment' | 'waitlist' | 'contact';
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  name: string;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  preferredContactMethod: 'email' | 'phone' | 'viber' | 'telegram' | 'whatsapp';
  locale: 'uk' | 'ru' | 'en';
  sourceType: 'contact' | 'booking' | 'corporate' | 'course' | 'collection' | 'atelier';
  consent: {
    version: string;
    acceptedAt: string;
  };
  firstTouch?: {
    landingPage?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmContent?: string | null;
    utmTerm?: string | null;
  };
  lastTouch?: {
    landingPage?: string | null;
    referrer?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmContent?: string | null;
    utmTerm?: string | null;
  };
  duplicateState: 'unique' | 'possible-duplicate' | 'merged';
  mergedInto?: (string | null) | Lead;
  assignee?: (string | null) | User;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-requests".
 */
export interface BookingRequest {
  id: string;
  idempotencyKey: string;
  /**
   * One-way request fingerprint used for abuse controls.
   */
  requestFingerprint: string;
  lead: string | Lead;
  service: string | Service;
  offer?: (string | null) | Offer;
  course?: (string | null) | Course;
  fashionCollection?: (string | null) | FashionCollection;
  inquiryType: 'private' | 'corporate';
  requestMode: 'inquiry' | 'booking-request' | 'deposit' | 'instant-payment' | 'waitlist';
  format: 'online' | 'studio' | 'remote-atelier' | 'in-person' | 'hybrid';
  preferredDates?:
    | {
        preferredAt: string;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  currency?: ('EUR' | 'UAH') | null;
  sourcePage: string;
  referrer?: string | null;
  attribution?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmContent?: string | null;
    utmTerm?: string | null;
  };
  status:
    | 'new'
    | 'qualified'
    | 'waiting-for-client'
    | 'awaiting-schedule'
    | 'awaiting-payment'
    | 'confirmed'
    | 'completed'
    | 'cancelled'
    | 'closed';
  internalNotes?: string | null;
  paymentOrder?: (string | null) | PaymentOrder;
  consentVersion: string;
  consentAcceptedAt: string;
  notificationStatus: 'pending' | 'sent' | 'failed';
  notificationError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-orders".
 */
export interface PaymentOrder {
  id: string;
  orderUUID: string;
  bookingRequest: string | BookingRequest;
  commercialSnapshot: {
    offerID: string;
    title: string;
    sku: string;
    termsVersion: string;
  };
  provider: 'stripe' | 'liqpay' | 'fondy';
  providerOrderID?: string | null;
  providerPaymentID?: string | null;
  /**
   * Integer minor units, immutable after order creation.
   */
  amount: number;
  currency: 'EUR' | 'UAH';
  mode: 'test' | 'live';
  checkoutURL?: string | null;
  checkoutExpiresAt?: string | null;
  status:
    | 'created'
    | 'pending'
    | 'requires-action'
    | 'paid'
    | 'failed'
    | 'cancelled'
    | 'expired'
    | 'partially-refunded'
    | 'refunded'
    | 'disputed';
  idempotencyKey: string;
  paidAmount?: number | null;
  refundedAmount?: number | null;
  safeFailureCode?: string | null;
  paidAt?: string | null;
  refundedAt?: string | null;
  notificationStatus: 'pending' | 'sent' | 'failed';
  notificationError?: string | null;
  auditNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: string;
  provider: 'stripe' | 'liqpay' | 'fondy';
  providerEventID: string;
  eventType: string;
  receivedAt: string;
  processingStatus: 'received' | 'processed' | 'ignored' | 'failed';
  paymentOrder?: (string | null) | PaymentOrder;
  retryCount: number;
  sanitizedError?: string | null;
  payloadHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'directions';
          value: string | Direction;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'courses';
          value: string | Course;
        } | null)
      | ({
          relationTo: 'fashion-collections';
          value: string | FashionCollection;
        } | null)
      | ({
          relationTo: 'portfolio-cases';
          value: string | PortfolioCase;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'directions';
        value: string | Direction;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'offers';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'courses';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'fashion-collections';
        value: string | FashionCollection;
      } | null)
    | ({
        relationTo: 'portfolio-cases';
        value: string | PortfolioCase;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'booking-requests';
        value: string | BookingRequest;
      } | null)
    | ({
        relationTo: 'payment-orders';
        value: string | PaymentOrder;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: string | WebhookEvent;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  active?: T;
  adminLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  internalLabel?: T;
  alt?: T;
  source?: T;
  usageRightsStatus?: T;
  modelReleaseStatus?: T;
  publicVisibility?: T;
  isRealClientProof?: T;
  replacementPriority?: T;
  creator?: T;
  creditLine?: T;
  allowedUsageContexts?: T;
  rightsExpiry?: T;
  sourceMetadata?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        editorial?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions_select".
 */
export interface DirectionsSelect<T extends boolean = true> {
  legacyKey?: T;
  slug?: T;
  title?: T;
  summary?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  canonicalKey?: T;
  eyebrow?: T;
  narrative?: T;
  processTitle?: T;
  formatsTitle?: T;
  formatNotes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  outcomesTitle?: T;
  ctaTitle?: T;
  ctaSummary?: T;
  ctaService?: T;
  ctaLabel?: T;
  diagnosticLabel?: T;
  faqTitle?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  countLabel?: T;
  availabilityValue?: T;
  availabilityLabel?: T;
  fittingValue?: T;
  fittingLabel?: T;
  catalogueTitle?: T;
  catalogueSummary?: T;
  materialsLabel?: T;
  inquiryTitle?: T;
  inquirySteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  heroMedia?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  relatedServices?: T;
  relatedCourses?: T;
  relatedCollections?: T;
  navigationVisible?: T;
  supplementaryLayout?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              heading?: T;
              body?: T;
              media?: T;
              mediaPosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relationGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              path?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  legacyKey?: T;
  slug?: T;
  title?: T;
  summary?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  primaryDirection?: T;
  secondaryDirections?: T;
  audience?: T;
  intro?: T;
  formatsTitle?: T;
  processTitle?: T;
  outcomeTitle?: T;
  commercialTitle?: T;
  commercialStatusCopy?: T;
  priceNote?: T;
  nextStepTitle?: T;
  nextStepSummary?: T;
  formats?: T;
  formatPresentation?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  timingNote?: T;
  qualification?: T;
  gallery?: T;
  relatedOffers?: T;
  relatedPortfolio?: T;
  relatedServices?: T;
  relatedCourses?: T;
  relatedCollections?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        action?: T;
      };
  supplementaryLayout?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              heading?: T;
              body?: T;
              media?: T;
              mediaPosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relationGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              path?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  legacyKey?: T;
  service?: T;
  course?: T;
  fashionCollection?: T;
  sku?: T;
  title?: T;
  shortDescription?: T;
  format?: T;
  pricingMode?: T;
  checkoutMode?: T;
  commercialStatus?: T;
  prices?:
    | T
    | {
        currency?: T;
        amount?: T;
        minAmount?: T;
        maxAmount?: T;
        id?: T;
      };
  durationMinutes?: T;
  sessions?: T;
  deposit?:
    | T
    | {
        amount?: T;
        percentage?: T;
      };
  effectiveFrom?: T;
  effectiveUntil?: T;
  termsVersion?: T;
  enabled?: T;
  sortOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  legacyKey?: T;
  slug?: T;
  title?: T;
  summary?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  direction?: T;
  description?: T;
  eyebrow?: T;
  serviceLabel?: T;
  audienceTitle?: T;
  formatTitle?: T;
  methodTitle?: T;
  prerequisitesTitle?: T;
  curriculumTitle?: T;
  curriculumSummary?: T;
  outcomesTitle?: T;
  outcomesSummary?: T;
  commercialTitle?: T;
  ctaTitle?: T;
  ctaSummary?: T;
  audience?: T;
  prerequisites?: T;
  sessions?: T;
  formats?: T;
  program?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  instructor?: T;
  credentials?: T;
  intakeNote?: T;
  relatedOffers?: T;
  media?: T;
  availability?: T;
  relatedServices?: T;
  relatedCollections?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        action?: T;
      };
  supplementaryLayout?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              heading?: T;
              body?: T;
              media?: T;
              mediaPosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relationGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              path?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fashion-collections_select".
 */
export interface FashionCollectionsSelect<T extends boolean = true> {
  legacyKey?: T;
  slug?: T;
  title?: T;
  summary?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  eyebrow?: T;
  narrative?: T;
  stylingNotes?: T;
  stylingTitle?: T;
  styling?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  factsTitle?: T;
  facts?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  inquiryTitle?: T;
  inquirySteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  materialsTitle?: T;
  availabilityTitle?: T;
  ctaTitle?: T;
  ctaSummary?: T;
  serviceLabel?: T;
  collectionType?: T;
  collaborationCredits?: T;
  materials?:
    | T
    | {
        material?: T;
        id?: T;
      };
  pieces?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  season?: T;
  year?: T;
  gallery?: T;
  videoURL?: T;
  availability?: T;
  relatedOffers?: T;
  relatedServices?: T;
  relatedCourse?: T;
  rightsAndCredits?: T;
  cta?:
    | T
    | {
        label?: T;
        action?: T;
      };
  supplementaryLayout?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              heading?: T;
              body?: T;
              media?: T;
              mediaPosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relationGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              path?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-cases_select".
 */
export interface PortfolioCasesSelect<T extends boolean = true> {
  legacyKey?: T;
  slug?: T;
  title?: T;
  summary?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  clientType?: T;
  brief?: T;
  constraints?: T;
  research?: T;
  process?: T;
  result?: T;
  services?: T;
  media?: T;
  hasBeforeAfter?: T;
  consentReference?: T;
  isRealClientProof?: T;
  usageRightsStatus?: T;
  approvalStatus?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  legacyKey?: T;
  quote?: T;
  attribution?: T;
  roleOrCompany?: T;
  relatedService?: T;
  relatedCase?: T;
  consentStatus?: T;
  proofReference?: T;
  enabled?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  legacyKey?: T;
  slug?: T;
  title?: T;
  summary?: T;
  enabled?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  pageType?: T;
  eyebrow?: T;
  body?: T;
  studioSignals?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  methodEyebrow?: T;
  methodTitle?: T;
  methodSteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  clientsTitle?: T;
  clientsSummary?: T;
  privateTitle?: T;
  corporateTitle?: T;
  directionsTitle?: T;
  ctaTitle?: T;
  ctaSummary?: T;
  formTitle?: T;
  formSummary?: T;
  heroMediaLabel?: T;
  standardsTitle?: T;
  standards?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  recordTitle?: T;
  recordSummary?: T;
  recordItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  currentTitle?: T;
  currentItems?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  flowTitle?: T;
  flowItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  secondaryCTALabel?: T;
  emptyEyebrow?: T;
  emptyTitle?: T;
  emptySummary?: T;
  emptyAction?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              heading?: T;
              body?: T;
              media?: T;
              mediaPosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relationGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              path?: T;
              id?: T;
              blockName?: T;
            };
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        media?: T;
        id?: T;
      };
  contactConfiguration?:
    | T
    | {
        showMap?: T;
        corporateContext?: T;
      };
  legalVersion?: T;
  effectiveDate?: T;
  cta?:
    | T
    | {
        label?: T;
        action?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  preferredContactMethod?: T;
  locale?: T;
  sourceType?: T;
  consent?:
    | T
    | {
        version?: T;
        acceptedAt?: T;
      };
  firstTouch?:
    | T
    | {
        landingPage?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmContent?: T;
        utmTerm?: T;
      };
  lastTouch?:
    | T
    | {
        landingPage?: T;
        referrer?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmContent?: T;
        utmTerm?: T;
      };
  duplicateState?: T;
  mergedInto?: T;
  assignee?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-requests_select".
 */
export interface BookingRequestsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  requestFingerprint?: T;
  lead?: T;
  service?: T;
  offer?: T;
  course?: T;
  fashionCollection?: T;
  inquiryType?: T;
  requestMode?: T;
  format?: T;
  preferredDates?:
    | T
    | {
        preferredAt?: T;
        id?: T;
      };
  message?: T;
  currency?: T;
  sourcePage?: T;
  referrer?: T;
  attribution?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmContent?: T;
        utmTerm?: T;
      };
  status?: T;
  internalNotes?: T;
  paymentOrder?: T;
  consentVersion?: T;
  consentAcceptedAt?: T;
  notificationStatus?: T;
  notificationError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-orders_select".
 */
export interface PaymentOrdersSelect<T extends boolean = true> {
  orderUUID?: T;
  bookingRequest?: T;
  commercialSnapshot?:
    | T
    | {
        offerID?: T;
        title?: T;
        sku?: T;
        termsVersion?: T;
      };
  provider?: T;
  providerOrderID?: T;
  providerPaymentID?: T;
  amount?: T;
  currency?: T;
  mode?: T;
  checkoutURL?: T;
  checkoutExpiresAt?: T;
  status?: T;
  idempotencyKey?: T;
  paidAmount?: T;
  refundedAmount?: T;
  safeFailureCode?: T;
  paidAt?: T;
  refundedAt?: T;
  notificationStatus?: T;
  notificationError?: T;
  auditNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  providerEventID?: T;
  eventType?: T;
  receivedAt?: T;
  processingStatus?: T;
  paymentOrder?: T;
  retryCount?: T;
  sanitizedError?: T;
  payloadHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroSummary: string;
  heroMedia?: (string | null) | Media;
  primaryCTA: {
    label: string;
    path: string;
  };
  secondaryCTA: {
    label: string;
    path: string;
  };
  method?:
    | {
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  selectedDirections?: (string | Direction)[] | null;
  selectedServices?: (string | Service)[] | null;
  selectedOffers?: (string | Offer)[] | null;
  selectedCourses?: (string | Course)[] | null;
  selectedCollections?: (string | FashionCollection)[] | null;
  selectedPortfolio?: (string | PortfolioCase)[] | null;
  studioIntro: string;
  serviceIntro: string;
  priceNote: string;
  methodEyebrow: string;
  methodTitle: string;
  methodDetails?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  studioEyebrow: string;
  studioTitle: string;
  serviceRailTitle: string;
  collectionRailTitle: string;
  portfolioNote: string;
  portfolioTitle: string;
  portfolioSummary: string;
  portfolioSignals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqTitle: string;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  sectionMedia?: {
    research?: (string | null) | Media;
    imagine?: (string | null) | Media;
    create?: (string | null) | Media;
    directions?: (string | null) | Media;
    studio?: (string | null) | Media;
    portfolio?: (string | null) | Media;
  };
  finalCTATitle: string;
  finalCTASummary: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navigation?:
    | {
        label: string;
        path: string;
        visible: boolean;
        external: boolean;
        accessibleLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  bookingLabel: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  email: string;
  phone: string;
  address: string;
  hours: string;
  responseTime: string;
  socialLinks?:
    | {
        platform: string;
        url: string;
        accessibleLabel: string;
        id?: string | null;
      }[]
    | null;
  legalNavigation?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  brandName: string;
  canonicalOrigin: string;
  defaultSocialImage?: (string | null) | Media;
  contacts: {
    email: string;
    phone: string;
    address: string;
    city: string;
    hours: string;
    actionLabel: string;
    actionPath: string;
    viberURL?: string | null;
  };
  uiLabels: {
    language: string;
    close: string;
    externalLink: string;
  };
  localeLabels: {
    uk: string;
    ru: string;
    en: string;
  };
  ga4MeasurementID?: string | null;
  map?: {
    provider?: ('none' | 'google' | 'openstreetmap') | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  maintenance: {
    enabled: boolean;
    message?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: string;
  timezone: string;
  enabledModes: ('inquiry' | 'booking-request' | 'deposit' | 'instant-payment' | 'waitlist')[];
  holdMinutes?: number | null;
  cancellationWindowHours?: number | null;
  providerRouting?:
    | {
        currency: 'EUR' | 'UAH';
        provider: 'stripe' | 'liqpay' | 'fondy';
        enabled: boolean;
        publicLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Environment-specific public recipient identifiers; never credentials.
   */
  notificationRecipients?:
    | {
        environment: 'local' | 'preview' | 'production';
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroSummary?: T;
  heroMedia?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        path?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
        path?: T;
      };
  method?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  selectedDirections?: T;
  selectedServices?: T;
  selectedOffers?: T;
  selectedCourses?: T;
  selectedCollections?: T;
  selectedPortfolio?: T;
  studioIntro?: T;
  serviceIntro?: T;
  priceNote?: T;
  methodEyebrow?: T;
  methodTitle?: T;
  methodDetails?:
    | T
    | {
        text?: T;
        id?: T;
      };
  studioEyebrow?: T;
  studioTitle?: T;
  serviceRailTitle?: T;
  collectionRailTitle?: T;
  portfolioNote?: T;
  portfolioTitle?: T;
  portfolioSummary?: T;
  portfolioSignals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqTitle?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sectionMedia?:
    | T
    | {
        research?: T;
        imagine?: T;
        create?: T;
        directions?: T;
        studio?: T;
        portfolio?: T;
      };
  finalCTATitle?: T;
  finalCTASummary?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        path?: T;
        visible?: T;
        external?: T;
        accessibleLabel?: T;
        id?: T;
      };
  bookingLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  hours?: T;
  responseTime?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        accessibleLabel?: T;
        id?: T;
      };
  legalNavigation?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  canonicalOrigin?: T;
  defaultSocialImage?: T;
  contacts?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        city?: T;
        hours?: T;
        actionLabel?: T;
        actionPath?: T;
        viberURL?: T;
      };
  uiLabels?:
    | T
    | {
        language?: T;
        close?: T;
        externalLink?: T;
      };
  localeLabels?:
    | T
    | {
        uk?: T;
        ru?: T;
        en?: T;
      };
  ga4MeasurementID?: T;
  map?:
    | T
    | {
        provider?: T;
        latitude?: T;
        longitude?: T;
      };
  maintenance?:
    | T
    | {
        enabled?: T;
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  timezone?: T;
  enabledModes?: T;
  holdMinutes?: T;
  cancellationWindowHours?: T;
  providerRouting?:
    | T
    | {
        currency?: T;
        provider?: T;
        enabled?: T;
        publicLabel?: T;
        id?: T;
      };
  notificationRecipients?:
    | T
    | {
        environment?: T;
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'directions';
          value: string | Direction;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'offers';
          value: string | Offer;
        } | null)
      | ({
          relationTo: 'courses';
          value: string | Course;
        } | null)
      | ({
          relationTo: 'fashion-collections';
          value: string | FashionCollection;
        } | null)
      | ({
          relationTo: 'portfolio-cases';
          value: string | PortfolioCase;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: string | Testimonial;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: ('home' | 'header' | 'footer') | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}