/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    products: Product;
    portfolio: Portfolio;
    collections: Collection;
    orders: Order;
    courses: Course;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'uk') | ('en' | 'ru' | 'uk')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ru' | 'uk';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role for access control
   */
  role: 'admin' | 'user';
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Images and documents for the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Localized alt text is required for accessibility and SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Styling and atelier services offered by PURITY
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Service name in this language
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Only published services are shown on the website
   */
  status: 'draft' | 'published';
  /**
   * Full service description with formatting
   */
  description?: string | null;
  /**
   * Brief description for cards and previews (1-2 sentences)
   */
  excerpt?: string | null;
  /**
   * Service category for filtering
   */
  category: 'styling' | 'atelier' | 'consulting' | 'shopping' | 'events';
  /**
   * How this service is delivered
   */
  format?: ('online' | 'studio' | 'onsite' | 'hybrid') | null;
  /**
   * Pricing information
   */
  pricing?: {
    /**
     * Price in Ukrainian Hryvnia
     */
    uah?: number | null;
    /**
     * Price in Euros
     */
    eur?: number | null;
    /**
     * Optional note (e.g., "Starting from", "Per hour")
     */
    priceNote?: string | null;
  };
  /**
   * Service duration (e.g., "2 hours", "1-2 days")
   */
  duration?: string | null;
  /**
   * Main image for the service page
   */
  heroImage?: (number | null) | Media;
  /**
   * How the service works (process steps)
   */
  steps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What client gets from this service
   */
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show on homepage featured section
   */
  featured?: boolean | null;
  /**
   * Allow online booking for this service
   */
  bookable?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Atelier products and clothing items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  status: 'draft' | 'published' | 'out-of-stock' | 'archived';
  /**
   * Show in featured products section
   */
  featured?: boolean | null;
  /**
   * Brief description for cards and previews
   */
  excerpt?: string | null;
  /**
   * Full product description
   */
  description?: string | null;
  /**
   * Stock Keeping Unit
   */
  sku?: string | null;
  /**
   * Product pricing in multiple currencies
   */
  pricing: {
    /**
     * Price in Ukrainian Hryvnia
     */
    uah: number;
    /**
     * Price in Euro (optional)
     */
    eur?: number | null;
    /**
     * Sale price in UAH (leave empty if not on sale)
     */
    salePrice?: number | null;
  };
  /**
   * Product images (first is main)
   */
  images?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  category: 'dresses' | 'tops' | 'bottoms' | 'outerwear' | 'accessories' | 'bags' | 'jewelry';
  /**
   * Product specifications
   */
  details?: {
    material?: string | null;
    /**
     * Care instructions
     */
    care?: string | null;
    sizes?: ('xs' | 's' | 'm' | 'l' | 'xl' | 'one-size')[] | null;
    colors?:
      | {
          name: string;
          /**
           * Hex color code (e.g., #000000)
           */
          hex?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Before/after transformations and client work
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  /**
   * Project title (can include client first name)
   */
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Only published items are visible on the site
   */
  status: 'draft' | 'published';
  category?: ('styling' | 'wardrobe-audit' | 'transformation' | 'event' | 'shopping') | null;
  /**
   * Story behind the transformation
   */
  description?: string | null;
  /**
   * Before photo
   */
  beforeImage: number | Media;
  /**
   * After photo
   */
  afterImage: number | Media;
  /**
   * Additional photos from the project
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Which services were used for this project
   */
  servicesUsed?: (number | Service)[] | null;
  /**
   * Optional client testimonial
   */
  testimonial?: {
    quote?: string | null;
    /**
     * First name only for privacy
     */
    clientName?: string | null;
    rating?: number | null;
  };
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  /**
   * Date to display for this project
   */
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Curated fashion collections and lookbooks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  /**
   * Collection name (e.g., "Autumn Essentials 2024")
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Only published collections are public
   */
  status: 'draft' | 'published';
  season?: ('spring' | 'summer' | 'autumn' | 'winter' | 'all-season') | null;
  /**
   * Collection story and inspiration
   */
  description?: string | null;
  /**
   * Main collection image
   */
  coverImage?: (number | null) | Media;
  /**
   * Lookbook images
   */
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  /**
   * When this collection was released
   */
  releaseDate?: string | null;
  /**
   * Products featured in this collection
   */
  linkedProducts?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'processing' | 'paid' | 'failed' | 'cancelled' | 'completed' | 'refunded';
  items: {
    type: 'service' | 'product';
    name: string;
    slug: string;
    price: number;
    quantity: number;
    bookingDate?: string | null;
    bookingTime?: string | null;
    id?: string | null;
  }[];
  subtotal: number;
  total: number;
  currency: 'UAH' | 'EUR';
  customer: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    address?: string | null;
    city?: string | null;
    country?: string | null;
    postalCode?: string | null;
  };
  notes?: string | null;
  paymentProvider: 'stripe' | 'liqpay';
  /**
   * Stripe PaymentIntent ID or LiqPay order ID
   */
  paymentIntentId?: string | null;
  /**
   * Raw status from payment provider
   */
  paymentStatus?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Educational courses and workshops on styling and fashion
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Course title in this language
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated)
   */
  slug: string;
  /**
   * Course category for filtering
   */
  category: 'personal-styling' | 'color-analysis' | 'wardrobe-audit' | 'shopping' | 'professional' | 'masterclass';
  /**
   * Target audience experience level
   */
  level: 'beginner' | 'intermediate' | 'advanced' | 'all';
  status: 'draft' | 'published' | 'coming-soon' | 'archived';
  /**
   * Brief description for cards and previews
   */
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  duration: {
    value: number;
    unit: 'hours' | 'days' | 'weeks' | 'months';
  };
  format: 'online' | 'in-person' | 'hybrid';
  price: {
    amount: number;
    currency: 'UAH' | 'EUR';
    /**
     * Early bird discount price (optional)
     */
    earlyBirdAmount?: number | null;
  };
  curriculum?:
    | {
        module: string;
        topics?:
          | {
              topic: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  instructor: {
    name: string;
    title?: string | null;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  testimonials?:
    | {
        name: string;
        quote: string;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  upcomingDates?:
    | {
        startDate: string;
        endDate?: string | null;
        spotsAvailable?: number | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  description?: T;
  excerpt?: T;
  category?: T;
  format?: T;
  pricing?:
    | T
    | {
        uah?: T;
        eur?: T;
        priceNote?: T;
      };
  duration?: T;
  heroImage?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  bookable?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  featured?: T;
  excerpt?: T;
  description?: T;
  sku?: T;
  pricing?:
    | T
    | {
        uah?: T;
        eur?: T;
        salePrice?: T;
      };
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  category?: T;
  details?:
    | T
    | {
        material?: T;
        care?: T;
        sizes?: T;
        colors?:
          | T
          | {
              name?: T;
              hex?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  category?: T;
  description?: T;
  beforeImage?: T;
  afterImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  servicesUsed?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        clientName?: T;
        rating?: T;
      };
  featured?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  season?: T;
  description?: T;
  coverImage?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  featured?: T;
  releaseDate?: T;
  linkedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  items?:
    | T
    | {
        type?: T;
        name?: T;
        slug?: T;
        price?: T;
        quantity?: T;
        bookingDate?: T;
        bookingTime?: T;
        id?: T;
      };
  subtotal?: T;
  total?: T;
  currency?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        address?: T;
        city?: T;
        country?: T;
        postalCode?: T;
      };
  notes?: T;
  paymentProvider?: T;
  paymentIntentId?: T;
  paymentStatus?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  level?: T;
  status?: T;
  excerpt?: T;
  description?: T;
  featuredImage?: T;
  duration?:
    | T
    | {
        value?: T;
        unit?: T;
      };
  format?: T;
  price?:
    | T
    | {
        amount?: T;
        currency?: T;
        earlyBirdAmount?: T;
      };
  curriculum?:
    | T
    | {
        module?: T;
        topics?:
          | T
          | {
              topic?: T;
              id?: T;
            };
        id?: T;
      };
  instructor?:
    | T
    | {
        name?: T;
        title?: T;
        bio?: T;
        photo?: T;
      };
  testimonials?:
    | T
    | {
        name?: T;
        quote?: T;
        photo?: T;
        id?: T;
      };
  upcomingDates?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        spotsAvailable?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Site name used in meta tags and branding
   */
  siteName: string;
  /**
   * Short tagline for the site
   */
  tagline?: string | null;
  /**
   * Default meta description for SEO
   */
  description?: string | null;
  /**
   * Site logo
   */
  logo?: (number | null) | Media;
  /**
   * Site favicon (32x32 recommended)
   */
  favicon?: (number | null) | Media;
  contact: {
    /**
     * Primary contact email
     */
    email: string;
    /**
     * Contact phone number (international format)
     */
    phone?: string | null;
    /**
     * WhatsApp number (with country code)
     */
    whatsapp?: string | null;
    /**
     * Telegram username or link
     */
    telegram?: string | null;
    /**
     * Physical address
     */
    address?: string | null;
    /**
     * Working hours information
     */
    workingHours?: string | null;
  };
  social?: {
    /**
     * Instagram profile URL
     */
    instagram?: string | null;
    /**
     * Facebook page URL
     */
    facebook?: string | null;
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * Pinterest profile URL
     */
    pinterest?: string | null;
    /**
     * YouTube channel URL
     */
    youtube?: string | null;
  };
  currency?: {
    /**
     * Default currency for pricing display
     */
    default?: ('UAH' | 'EUR' | 'USD') | null;
    /**
     * For automatic currency conversion
     */
    exchangeRateEur?: number | null;
    exchangeRateUsd?: number | null;
  };
  payments?: {
    /**
     * Enable LiqPay payment method
     */
    enableLiqPay?: boolean | null;
    /**
     * Enable Stripe payment method
     */
    enableStripe?: boolean | null;
    /**
     * Enable bank transfer payment method
     */
    enableBankTransfer?: boolean | null;
  };
  booking?: {
    /**
     * Enable online booking
     */
    enabled?: boolean | null;
    /**
     * Minimum hours before appointment can be booked
     */
    leadTime?: number | null;
    /**
     * Maximum days in advance for booking
     */
    maxAdvanceBooking?: number | null;
    /**
     * Custom message for booking confirmation email
     */
    confirmationEmail?: string | null;
  };
  seo?: {
    /**
     * Default Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
    /**
     * Google Search Console verification code
     */
    googleSiteVerification?: string | null;
  };
  analytics?: {
    /**
     * Google Analytics 4 Measurement ID (G-XXXXXXX)
     */
    googleAnalyticsId?: string | null;
    /**
     * Facebook Pixel ID
     */
    facebookPixelId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        telegram?: T;
        address?: T;
        workingHours?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        linkedin?: T;
        pinterest?: T;
        youtube?: T;
      };
  currency?:
    | T
    | {
        default?: T;
        exchangeRateEur?: T;
        exchangeRateUsd?: T;
      };
  payments?:
    | T
    | {
        enableLiqPay?: T;
        enableStripe?: T;
        enableBankTransfer?: T;
      };
  booking?:
    | T
    | {
        enabled?: T;
        leadTime?: T;
        maxAdvanceBooking?: T;
        confirmationEmail?: T;
      };
  seo?:
    | T
    | {
        ogImage?: T;
        googleSiteVerification?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        facebookPixelId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}