/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as LangTransformationRouteImport } from './routes/$lang/transformation'
import { Route as LangSchoolRouteImport } from './routes/$lang/school'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangContactsRouteImport } from './routes/$lang/contacts'
import { Route as LangBookRouteImport } from './routes/$lang/book'
import { Route as AdminContentRouteRouteImport } from './routes/admin/content/route'
import { Route as LangResearchRouteRouteImport } from './routes/$lang/research/route'
import { Route as LangRealisationRouteRouteImport } from './routes/$lang/realisation/route'
import { Route as LangPortfolioRouteRouteImport } from './routes/$lang/portfolio/route'
import { Route as LangCollectionsRouteRouteImport } from './routes/$lang/collections/route'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as LangResearchIndexRouteImport } from './routes/$lang/research/index'
import { Route as LangRealisationIndexRouteImport } from './routes/$lang/realisation/index'
import { Route as LangPortfolioIndexRouteImport } from './routes/$lang/portfolio/index'
import { Route as LangCollectionsIndexRouteImport } from './routes/$lang/collections/index'
import { Route as LangResearchSlugRouteImport } from './routes/$lang/research/$slug'
import { Route as LangRealisationAtelierRouteImport } from './routes/$lang/realisation/atelier'
import { Route as LangRealisationSlugRouteImport } from './routes/$lang/realisation/$slug'
import { Route as LangPortfolioSlugRouteImport } from './routes/$lang/portfolio/$slug'
import { Route as LangCollectionsSlugRouteImport } from './routes/$lang/collections/$slug'
import { Route as AdminContentKindIndexRouteImport } from './routes/admin/content/$kind/index'
import { Route as AdminContentKindSlugRouteImport } from './routes/admin/content/$kind/$slug'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LangTransformationRoute = LangTransformationRouteImport.update({
  id: '/transformation',
  path: '/transformation',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSchoolRoute = LangSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactsRoute = LangContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookRoute = LangBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminContentRouteRoute = AdminContentRouteRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LangResearchRouteRoute = LangResearchRouteRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRealisationRouteRoute = LangRealisationRouteRouteImport.update({
  id: '/realisation',
  path: '/realisation',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPortfolioRouteRoute = LangPortfolioRouteRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCollectionsRouteRoute = LangCollectionsRouteRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContentRouteRoute,
} as any)
const LangResearchIndexRoute = LangResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangResearchRouteRoute,
} as any)
const LangRealisationIndexRoute = LangRealisationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRealisationRouteRoute,
} as any)
const LangPortfolioIndexRoute = LangPortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPortfolioRouteRoute,
} as any)
const LangCollectionsIndexRoute = LangCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangCollectionsRouteRoute,
} as any)
const LangResearchSlugRoute = LangResearchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangResearchRouteRoute,
} as any)
const LangRealisationAtelierRoute = LangRealisationAtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => LangRealisationRouteRoute,
} as any)
const LangRealisationSlugRoute = LangRealisationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangRealisationRouteRoute,
} as any)
const LangPortfolioSlugRoute = LangPortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangPortfolioRouteRoute,
} as any)
const LangCollectionsSlugRoute = LangCollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangCollectionsRouteRoute,
} as any)
const AdminContentKindIndexRoute = AdminContentKindIndexRouteImport.update({
  id: '/$kind/',
  path: '/$kind/',
  getParentRoute: () => AdminContentRouteRoute,
} as any)
const AdminContentKindSlugRoute = AdminContentKindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => AdminContentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$lang/collections': typeof LangCollectionsRouteRouteWithChildren
  '/$lang/portfolio': typeof LangPortfolioRouteRouteWithChildren
  '/$lang/realisation': typeof LangRealisationRouteRouteWithChildren
  '/$lang/research': typeof LangResearchRouteRouteWithChildren
  '/admin/content': typeof AdminContentRouteRouteWithChildren
  '/$lang/book': typeof LangBookRoute
  '/$lang/contacts': typeof LangContactsRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/school': typeof LangSchoolRoute
  '/$lang/transformation': typeof LangTransformationRoute
  '/admin/login': typeof AdminLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/collections/$slug': typeof LangCollectionsSlugRoute
  '/$lang/portfolio/$slug': typeof LangPortfolioSlugRoute
  '/$lang/realisation/$slug': typeof LangRealisationSlugRoute
  '/$lang/realisation/atelier': typeof LangRealisationAtelierRoute
  '/$lang/research/$slug': typeof LangResearchSlugRoute
  '/$lang/collections/': typeof LangCollectionsIndexRoute
  '/$lang/portfolio/': typeof LangPortfolioIndexRoute
  '/$lang/realisation/': typeof LangRealisationIndexRoute
  '/$lang/research/': typeof LangResearchIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/content/$kind/$slug': typeof AdminContentKindSlugRoute
  '/admin/content/$kind/': typeof AdminContentKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/book': typeof LangBookRoute
  '/$lang/contacts': typeof LangContactsRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/school': typeof LangSchoolRoute
  '/$lang/transformation': typeof LangTransformationRoute
  '/admin/login': typeof AdminLoginRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/collections/$slug': typeof LangCollectionsSlugRoute
  '/$lang/portfolio/$slug': typeof LangPortfolioSlugRoute
  '/$lang/realisation/$slug': typeof LangRealisationSlugRoute
  '/$lang/realisation/atelier': typeof LangRealisationAtelierRoute
  '/$lang/research/$slug': typeof LangResearchSlugRoute
  '/$lang/collections': typeof LangCollectionsIndexRoute
  '/$lang/portfolio': typeof LangPortfolioIndexRoute
  '/$lang/realisation': typeof LangRealisationIndexRoute
  '/$lang/research': typeof LangResearchIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/content/$kind/$slug': typeof AdminContentKindSlugRoute
  '/admin/content/$kind': typeof AdminContentKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$lang/collections': typeof LangCollectionsRouteRouteWithChildren
  '/$lang/portfolio': typeof LangPortfolioRouteRouteWithChildren
  '/$lang/realisation': typeof LangRealisationRouteRouteWithChildren
  '/$lang/research': typeof LangResearchRouteRouteWithChildren
  '/admin/content': typeof AdminContentRouteRouteWithChildren
  '/$lang/book': typeof LangBookRoute
  '/$lang/contacts': typeof LangContactsRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/school': typeof LangSchoolRoute
  '/$lang/transformation': typeof LangTransformationRoute
  '/admin/login': typeof AdminLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/collections/$slug': typeof LangCollectionsSlugRoute
  '/$lang/portfolio/$slug': typeof LangPortfolioSlugRoute
  '/$lang/realisation/$slug': typeof LangRealisationSlugRoute
  '/$lang/realisation/atelier': typeof LangRealisationAtelierRoute
  '/$lang/research/$slug': typeof LangResearchSlugRoute
  '/$lang/collections/': typeof LangCollectionsIndexRoute
  '/$lang/portfolio/': typeof LangPortfolioIndexRoute
  '/$lang/realisation/': typeof LangRealisationIndexRoute
  '/$lang/research/': typeof LangResearchIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/content/$kind/$slug': typeof AdminContentKindSlugRoute
  '/admin/content/$kind/': typeof AdminContentKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/$lang/collections'
    | '/$lang/portfolio'
    | '/$lang/realisation'
    | '/$lang/research'
    | '/admin/content'
    | '/$lang/book'
    | '/$lang/contacts'
    | '/$lang/privacy'
    | '/$lang/school'
    | '/$lang/transformation'
    | '/admin/login'
    | '/$lang/'
    | '/admin/'
    | '/$lang/collections/$slug'
    | '/$lang/portfolio/$slug'
    | '/$lang/realisation/$slug'
    | '/$lang/realisation/atelier'
    | '/$lang/research/$slug'
    | '/$lang/collections/'
    | '/$lang/portfolio/'
    | '/$lang/realisation/'
    | '/$lang/research/'
    | '/admin/content/'
    | '/admin/content/$kind/$slug'
    | '/admin/content/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/book'
    | '/$lang/contacts'
    | '/$lang/privacy'
    | '/$lang/school'
    | '/$lang/transformation'
    | '/admin/login'
    | '/$lang'
    | '/admin'
    | '/$lang/collections/$slug'
    | '/$lang/portfolio/$slug'
    | '/$lang/realisation/$slug'
    | '/$lang/realisation/atelier'
    | '/$lang/research/$slug'
    | '/$lang/collections'
    | '/$lang/portfolio'
    | '/$lang/realisation'
    | '/$lang/research'
    | '/admin/content'
    | '/admin/content/$kind/$slug'
    | '/admin/content/$kind'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/$lang/collections'
    | '/$lang/portfolio'
    | '/$lang/realisation'
    | '/$lang/research'
    | '/admin/content'
    | '/$lang/book'
    | '/$lang/contacts'
    | '/$lang/privacy'
    | '/$lang/school'
    | '/$lang/transformation'
    | '/admin/login'
    | '/$lang/'
    | '/admin/'
    | '/$lang/collections/$slug'
    | '/$lang/portfolio/$slug'
    | '/$lang/realisation/$slug'
    | '/$lang/realisation/atelier'
    | '/$lang/research/$slug'
    | '/$lang/collections/'
    | '/$lang/portfolio/'
    | '/$lang/realisation/'
    | '/$lang/research/'
    | '/admin/content/'
    | '/admin/content/$kind/$slug'
    | '/admin/content/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$lang/transformation': {
      id: '/$lang/transformation'
      path: '/transformation'
      fullPath: '/$lang/transformation'
      preLoaderRoute: typeof LangTransformationRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/school': {
      id: '/$lang/school'
      path: '/school'
      fullPath: '/$lang/school'
      preLoaderRoute: typeof LangSchoolRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contacts': {
      id: '/$lang/contacts'
      path: '/contacts'
      fullPath: '/$lang/contacts'
      preLoaderRoute: typeof LangContactsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book': {
      id: '/$lang/book'
      path: '/book'
      fullPath: '/$lang/book'
      preLoaderRoute: typeof LangBookRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$lang/research': {
      id: '/$lang/research'
      path: '/research'
      fullPath: '/$lang/research'
      preLoaderRoute: typeof LangResearchRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/realisation': {
      id: '/$lang/realisation'
      path: '/realisation'
      fullPath: '/$lang/realisation'
      preLoaderRoute: typeof LangRealisationRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/portfolio': {
      id: '/$lang/portfolio'
      path: '/portfolio'
      fullPath: '/$lang/portfolio'
      preLoaderRoute: typeof LangPortfolioRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/collections': {
      id: '/$lang/collections'
      path: '/collections'
      fullPath: '/$lang/collections'
      preLoaderRoute: typeof LangCollectionsRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/$lang/research/': {
      id: '/$lang/research/'
      path: '/'
      fullPath: '/$lang/research/'
      preLoaderRoute: typeof LangResearchIndexRouteImport
      parentRoute: typeof LangResearchRouteRoute
    }
    '/$lang/realisation/': {
      id: '/$lang/realisation/'
      path: '/'
      fullPath: '/$lang/realisation/'
      preLoaderRoute: typeof LangRealisationIndexRouteImport
      parentRoute: typeof LangRealisationRouteRoute
    }
    '/$lang/portfolio/': {
      id: '/$lang/portfolio/'
      path: '/'
      fullPath: '/$lang/portfolio/'
      preLoaderRoute: typeof LangPortfolioIndexRouteImport
      parentRoute: typeof LangPortfolioRouteRoute
    }
    '/$lang/collections/': {
      id: '/$lang/collections/'
      path: '/'
      fullPath: '/$lang/collections/'
      preLoaderRoute: typeof LangCollectionsIndexRouteImport
      parentRoute: typeof LangCollectionsRouteRoute
    }
    '/$lang/research/$slug': {
      id: '/$lang/research/$slug'
      path: '/$slug'
      fullPath: '/$lang/research/$slug'
      preLoaderRoute: typeof LangResearchSlugRouteImport
      parentRoute: typeof LangResearchRouteRoute
    }
    '/$lang/realisation/atelier': {
      id: '/$lang/realisation/atelier'
      path: '/atelier'
      fullPath: '/$lang/realisation/atelier'
      preLoaderRoute: typeof LangRealisationAtelierRouteImport
      parentRoute: typeof LangRealisationRouteRoute
    }
    '/$lang/realisation/$slug': {
      id: '/$lang/realisation/$slug'
      path: '/$slug'
      fullPath: '/$lang/realisation/$slug'
      preLoaderRoute: typeof LangRealisationSlugRouteImport
      parentRoute: typeof LangRealisationRouteRoute
    }
    '/$lang/portfolio/$slug': {
      id: '/$lang/portfolio/$slug'
      path: '/$slug'
      fullPath: '/$lang/portfolio/$slug'
      preLoaderRoute: typeof LangPortfolioSlugRouteImport
      parentRoute: typeof LangPortfolioRouteRoute
    }
    '/$lang/collections/$slug': {
      id: '/$lang/collections/$slug'
      path: '/$slug'
      fullPath: '/$lang/collections/$slug'
      preLoaderRoute: typeof LangCollectionsSlugRouteImport
      parentRoute: typeof LangCollectionsRouteRoute
    }
    '/admin/content/$kind/': {
      id: '/admin/content/$kind/'
      path: '/$kind'
      fullPath: '/admin/content/$kind/'
      preLoaderRoute: typeof AdminContentKindIndexRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/content/$kind/$slug': {
      id: '/admin/content/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/admin/content/$kind/$slug'
      preLoaderRoute: typeof AdminContentKindSlugRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
  }
}

interface LangCollectionsRouteRouteChildren {
  LangCollectionsSlugRoute: typeof LangCollectionsSlugRoute
  LangCollectionsIndexRoute: typeof LangCollectionsIndexRoute
}

const LangCollectionsRouteRouteChildren: LangCollectionsRouteRouteChildren = {
  LangCollectionsSlugRoute: LangCollectionsSlugRoute,
  LangCollectionsIndexRoute: LangCollectionsIndexRoute,
}

const LangCollectionsRouteRouteWithChildren =
  LangCollectionsRouteRoute._addFileChildren(LangCollectionsRouteRouteChildren)

interface LangPortfolioRouteRouteChildren {
  LangPortfolioSlugRoute: typeof LangPortfolioSlugRoute
  LangPortfolioIndexRoute: typeof LangPortfolioIndexRoute
}

const LangPortfolioRouteRouteChildren: LangPortfolioRouteRouteChildren = {
  LangPortfolioSlugRoute: LangPortfolioSlugRoute,
  LangPortfolioIndexRoute: LangPortfolioIndexRoute,
}

const LangPortfolioRouteRouteWithChildren =
  LangPortfolioRouteRoute._addFileChildren(LangPortfolioRouteRouteChildren)

interface LangRealisationRouteRouteChildren {
  LangRealisationSlugRoute: typeof LangRealisationSlugRoute
  LangRealisationAtelierRoute: typeof LangRealisationAtelierRoute
  LangRealisationIndexRoute: typeof LangRealisationIndexRoute
}

const LangRealisationRouteRouteChildren: LangRealisationRouteRouteChildren = {
  LangRealisationSlugRoute: LangRealisationSlugRoute,
  LangRealisationAtelierRoute: LangRealisationAtelierRoute,
  LangRealisationIndexRoute: LangRealisationIndexRoute,
}

const LangRealisationRouteRouteWithChildren =
  LangRealisationRouteRoute._addFileChildren(LangRealisationRouteRouteChildren)

interface LangResearchRouteRouteChildren {
  LangResearchSlugRoute: typeof LangResearchSlugRoute
  LangResearchIndexRoute: typeof LangResearchIndexRoute
}

const LangResearchRouteRouteChildren: LangResearchRouteRouteChildren = {
  LangResearchSlugRoute: LangResearchSlugRoute,
  LangResearchIndexRoute: LangResearchIndexRoute,
}

const LangResearchRouteRouteWithChildren =
  LangResearchRouteRoute._addFileChildren(LangResearchRouteRouteChildren)

interface LangRouteRouteChildren {
  LangCollectionsRouteRoute: typeof LangCollectionsRouteRouteWithChildren
  LangPortfolioRouteRoute: typeof LangPortfolioRouteRouteWithChildren
  LangRealisationRouteRoute: typeof LangRealisationRouteRouteWithChildren
  LangResearchRouteRoute: typeof LangResearchRouteRouteWithChildren
  LangBookRoute: typeof LangBookRoute
  LangContactsRoute: typeof LangContactsRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangSchoolRoute: typeof LangSchoolRoute
  LangTransformationRoute: typeof LangTransformationRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangCollectionsRouteRoute: LangCollectionsRouteRouteWithChildren,
  LangPortfolioRouteRoute: LangPortfolioRouteRouteWithChildren,
  LangRealisationRouteRoute: LangRealisationRouteRouteWithChildren,
  LangResearchRouteRoute: LangResearchRouteRouteWithChildren,
  LangBookRoute: LangBookRoute,
  LangContactsRoute: LangContactsRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangSchoolRoute: LangSchoolRoute,
  LangTransformationRoute: LangTransformationRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface AdminContentRouteRouteChildren {
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminContentKindSlugRoute: typeof AdminContentKindSlugRoute
  AdminContentKindIndexRoute: typeof AdminContentKindIndexRoute
}

const AdminContentRouteRouteChildren: AdminContentRouteRouteChildren = {
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminContentKindSlugRoute: AdminContentKindSlugRoute,
  AdminContentKindIndexRoute: AdminContentKindIndexRoute,
}

const AdminContentRouteRouteWithChildren =
  AdminContentRouteRoute._addFileChildren(AdminContentRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminContentRouteRoute: typeof AdminContentRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContentRouteRoute: AdminContentRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
